// <auto-generated />
using System;
using Crud.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crud.WebAPI.Migrations
{
    [DbContext(typeof(CrudContext))]
    partial class CrudContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Crud.WebAPI.Models.Fornecedor", b =>
                {
                    b.Property<int>("CodigoFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CidadeFornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DescricaoFornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("CodigoFornecedor");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("Crud.WebAPI.Models.Produtos", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodigoFornecedor")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SituacaoProduto")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("CodigoProduto");

                    b.HasIndex("CodigoFornecedor");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Crud.WebAPI.Models.Produtos", b =>
                {
                    b.HasOne("Crud.WebAPI.Models.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("CodigoFornecedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
